name: Frends.FTP.DownloadFiles Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/release.yml
    with:
      workdir: Frends.FTP.DownloadFiles

    secrets:
      feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}