name: ListFiles build main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.FTP.ListFiles/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.FTP.ListFiles
      prebuild_command: docker-compose -f Frends.FTP.ListFiles.Tests/docker-compose.yml up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}