name: ListFiles build test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.FTP.ListFiles/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.FTP.ListFiles
      env_var_name_1: HiQ_FTP_Host
      env_var_name_2: HiQ_FTP_User
      env_var_name_3: HiQ_FTP_Password
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.HIQ_FTP_HOST }}
      env_var_value_2: ${{ secrets.HIQ_FTP_USER }}
      env_var_value_3: ${{ secrets.HIQ_FTP_PASSWORD }}