name: Frends.FTP.UploadFiles Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.FTP.UploadFiles/**'
  workflow_dispatch:


jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@ISSUE-9
    with:
      workdir: Frends.FTP.UploadFiles
      prebuild_command: "docker-compose up -d -f Frends.FTP.UploadFiles.Tests/docker-compose.yml"
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}