name: UploadFiles Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.FTP.UploadFiles/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@BugDebuggingFTP
    with:
      workdir: Frends.FTP.UploadFiles
      prebuild_command: docker-compose -f Frends.FTP.UploadFiles.Tests/docker-compose.yml up
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}