name: WriteFile Main

on:
  push:
    branches:
      - main
    paths:
      - 'Frends.FTP.WriteFile/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.FTP.WriteFile
      prebuild_command: docker-compose -f Frends.FTP.WriteFile.Tests/docker-compose.yml up -d
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}